# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0009_auto_20161010_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='profile-photo'),
        ),
    ]
