# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0010_auto_20161010_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile-photo/default.jpg', upload_to='profile-photo'),
        ),
    ]
