# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_comment',
            field=models.BooleanField(default=False),
        ),
    ]
