# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 01:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0014_post_has_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='has_comment',
        ),
        migrations.AddField(
            model_name='post',
            name='max_comment_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
